import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

export const useSettingsStore = defineStore('settings', () => {
  const settings = {
    af_gain: {desc: 'AF GAIN', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    agc: {desc: 'AGC', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    apf: {desc: 'APF ON/OFF', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    apf_freq: {desc: 'APF FREQ', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    antenna_tuner_control: {desc: 'ANTENNA TUNER CONTROL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    auto_notch: {desc: 'AUTO NOTCH', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    break_in: {desc: 'BREAK-IN', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    busy: {desc: 'BUSY', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    clar: {desc: 'CLAR', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    contour_freq: {desc: 'CONTOUR FREQ', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    contour_on: {desc: 'CONTOUR ON/OFF', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    ctcss: {desc: 'CTCSS MODE', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    ctcss_tone_frequency: {desc: 'CTCSS TONE FREQUENCY', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    cw_break_in_delay_time: {desc: 'CW BREAK-IN DELAY TIME', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    cw_spot: {desc: 'CW SPOT', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    // date: {desc: 'DATE', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    dcs_tone_frequency: {desc: 'DCS TONE FREQUENCY', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    fast_step: {desc: 'FAST STEP', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    function_tx: {desc: 'FUNCTION TX', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    if_shift: {desc: 'IF-SHIFT', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    // information: {desc: 'INFORMATION', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    key_pitch: {desc: 'KEY PITCH', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    key_speed: {desc: 'KEY SPEED', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    keyer: {desc: 'KEYER', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    lock: {desc: 'LOCK', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    manual_notch_level: {desc: 'MANUAL NOTCH LEVEL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    manual_notch: {desc: 'MANUAL NOTCH', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    memory_channel: {desc: 'MEMORY CHANNEL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    meter_sw: {desc: 'METER SWITCH', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    mic_gain: {desc: 'MIC GAIN', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    mode: {desc: 'MODE', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    monitor: {desc: 'MONITOR', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    monitor_level: {desc: 'MONITOR LEVEL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    mox_set: {desc: 'MOX SET', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    narrow: {desc: 'NARROW', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    noise_blanker_level: {desc: 'NOISE BLANKER LEVEL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    noise_blanker: {desc: 'NOISE BLANKER', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    noise_reduction: {desc: 'NOISE REDUCTION', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    noise_reduction_level: {desc: 'NOISE REDUCTION LEVEL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    offset: {desc: 'OFFSET (REPEATER SHIFT)', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    // opposite_band_information: {desc: 'OPPOSITE BAND INFORMATION', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    parametric_microphone_equalizer: {desc: 'PARAMETRIC MICROPHONE EQUALIZER', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    pll_unlock_status: {desc: 'PLL UNLOCK STATUS', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    power_level: {desc: 'POWER CONTROL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    pre_amp: {desc: 'PRE-AMP (IPO)', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    radio_information_hi_swr: {desc: 'RADIO INFORMATION HI SWR', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    radio_information_play: {desc: 'RADIO INFORMATION PLAY', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    radio_information_rec: {desc: 'RADIO INFORMATION REC', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    radio_information_tx_led: {desc: 'RADIO INFORMATION TX LED', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    radio_information_vfo_a_rx: {desc: 'RADIO INFORMATION VFO-A RX', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    radio_information_vfo_a_tx: {desc: 'RADIO INFORMATION VFO-A TX', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    radio_information_vfo_b_tx: {desc: 'RADIO INFORMATION VFO-B TX', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    // radio_status: {desc: 'RADIO STATUS', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    read_meter_alc: {desc: 'READ METER ALC', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    read_meter_front_panel: {desc: 'READ METER FRONT PANEL', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    read_meter_swr: {desc: 'READ METER SWR', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    rf_attenuator: {desc: 'RF ATTENUATOR', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    rf_gain: {desc: 'RF GAIN', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    s_meter_reading: {desc: 'S-METER READING', value: ref(null), all: ref(false), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    speech_processor: {desc: 'SPEECH PROCESSOR', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    speech_processor_level: {desc: 'SPEECH PROCESSOR LEVEL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    squelch_level: {desc: 'SQUELCH LEVEL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    // time: {desc: 'TIME', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    // time_differential: {desc: 'TIME DIFFERENTIAL', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    transmit: {desc: 'TRANSMIT', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    tx_clar: {desc: 'TX CLAR', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    txw: {desc: 'TXW', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    vfo_a: {desc: 'VFO-A', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    vfo_b: {desc: 'VFO-B', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    vox_delay_time: {desc: 'VOX DELAY TIME', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    vox_gain: {desc: 'VOX GAIN', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    vox: {desc: 'VOX', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
    width: {desc: 'WIDTH', value: ref(null), all: ref(true), changed: ref(false), fav: ref(false), saved: ref(false), unavailable: ref(false)},
  }

  return { settings }
})
