import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

export const useSettingsStore = defineStore('settings', () => {
	return {
    af_gain: ref({ desc: 'AF GAIN', value: null, all: true, changed: false, fav: false, saved: false}),
    agc: ref({desc: 'AGC', value: null, all: true, changed: false, fav: false, saved: false}),
    apf: ref({ desc: 'APF ON/OFF', value: null, all: true, changed: false, fav: false, saved: false}),
    apf_freq: ref({ desc: 'APF FREQ', value: null, all: true, changed: false, fav: false, saved: false}),
    auto_notch: ref({ desc: 'AUTO NOTCH', value: null, all: true, changed: false, fav: false, saved: false}),
    break_in: ref({ desc: 'BREAK-IN', value: null, all: true, changed: false, fav: false, saved: false}),
    busy: ref({ desc: 'BUSY', value: null, all: true, changed: false, fav: false, saved: false}),
    clar: ref({ desc: 'CLAR', value: null, all: true, changed: false, fav: false, saved: false}),
    contour_freq: ref({ desc: 'CONTOUR FREQ', value: null, all: true, changed: false, fav: false, saved: false}),
    contour_on: ref({ desc: 'CONTOUR ON/OFF', value: null, all: true, changed: false, fav: false, saved: false}),
    ctcss: ref({ desc: 'CTCSS', value: null, all: true, changed: false, fav: false, saved: false}),
    ctcss_tone_frequency: ref({ desc: 'CTCSS TONE FREQUENCY', value: null, all: true, changed: false, fav: false, saved: false}),
    cw_break_in_delay_time: ref({ desc: 'CW BREAK-IN DELAY TIME', value: null, all: true, changed: false, fav: false, saved: false}),
    cw_spot: ref({ desc: 'CW SPOT', value: null, all: true, changed: false, fav: false, saved: false}),
    date: ref({ desc: 'DATE', value: null, all: true, changed: false, fav: false, saved: false}),
    dcs_tone_frequency: ref({ desc: 'DCS TONE FREQUENCY', value: null, all: true, changed: false, fav: false, saved: false}),
    fast_step: ref({ desc: 'FAST STEP', value: null, all: true, changed: false, fav: false, saved: false}),
    function_tx: ref({ desc: 'FUNCTION TX', value: null, all: true, changed: false, fav: false, saved: false}),
    if_shift: ref({ desc: 'IF-SHIFT', value: null, all: true, changed: false, fav: false, saved: false}),
    // information: ref({ desc: 'INFORMATION', value: null, all: true, changed: false, fav: false, saved: false}),
    key_pitch: ref({ desc: 'KEY PITCH', value: null, all: true, changed: false, fav: false, saved: false}),
    key_speed: ref({ desc: 'KEY SPEED', value: null, all: true, changed: false, fav: false, saved: false}),
    keyer: ref({ desc: 'KEYER', value: null, all: true, changed: false, fav: false, saved: false}),
    lock: ref({ desc: 'LOCK', value: null, all: true, changed: false, fav: false, saved: false}),
    manual_notch_level: ref({ desc: 'MANUAL NOTCH LEVEL', value: null, all: true, changed: false, fav: false, saved: false}),
    manual_notch_on: ref({ desc: 'MANUAL NOTCH ON/OFF', value: null, all: true, changed: false, fav: false, saved: false}),
    memory_channel: ref({ desc: 'MEMORY CHANNEL', value: null, all: true, changed: false, fav: false, saved: false}),
    meter_sw: ref({ desc: 'METER SW', value: null, all: true, changed: false, fav: false, saved: false}),
    mic_gain: ref({ desc: 'MIC GAIN', value: null, all: true, changed: false, fav: false, saved: false}),
    mode: ref({ desc: 'MODE', value: null, all: true, changed: false, fav: false, saved: false}),
    monitor: ref({ desc: 'MONITOR ON/OFF', value: null, all: true, changed: false, fav: false, saved: false}),
    monitor_level: ref({ desc: 'MONITOR LEVEL', value: null, all: true, changed: false, fav: false, saved: false}),
    mox_set: ref({ desc: 'MOX SET', value: null, all: true, changed: false, fav: false, saved: false}),
    narrow: ref({ desc: 'NARROW', value: null, all: true, changed: false, fav: false, saved: false}),
    noise_blanker_level: ref({ desc: 'NOISE BLANKER LEVEL', value: null, all: true, changed: false, fav: false, saved: false}),
    noise_blanker_status: ref({ desc: 'NOISE BLANKER STATUS', value: null, all: true, changed: false, fav: false, saved: false}),
    noise_reduction: ref({ desc: 'NOISE REDUCTION', value: null, all: true, changed: false, fav: false, saved: false}),
    noise_reduction_level: ref({ desc: 'NOISE REDUCTION LEVEL', value: null, all: true, changed: false, fav: false, saved: false}),
    offset: ref({ desc: 'OFFSET (REPEATER SHIFT)', value: null, all: true, changed: false, fav: false, saved: false}),
    // opposite_band_information: ref({ desc: 'OPPOSITE BAND INFORMATION', value: null, all: true, changed: false, fav: false, saved: false}),
    parametric_microphone_equalizer: ref({ desc: 'PARAMETRIC MICROPHONE EQUALIZER', value: null, all: true, changed: false, fav: false, saved: false}),
    pll_unlock_status: ref({ desc: 'PLL UNLOCK STATUS', value: null, all: true, changed: false, fav: false, saved: false}),
    power_level: ref({ desc: 'POWER CONTROL', value: null, all: true, changed: false, fav: false, saved: false}),
    pre_amp: ref({ desc: 'PRE-AMP (IPO)', value: null, all: true, changed: false, fav: false, saved: false}),
    radio_information_hi_swr: ref({ desc: 'RADIO INFORMATION HI SWR', value: null, all: true, changed: false, fav: false, saved: false}),
    radio_information_play: ref({ desc: 'RADIO INFORMATION PLAY', value: null, all: true, changed: false, fav: false, saved: false}),
    radio_information_rec: ref({ desc: 'RADIO INFORMATION REC', value: null, all: true, changed: false, fav: false, saved: false}),
    radio_information_tx_led: ref({ desc: 'RADIO INFORMATION TX LED', value: null, all: true, changed: false, fav: false, saved: false}),
    radio_information_vfo_a_rx: ref({ desc: 'RADIO INFORMATION VFO-A RX', value: null, all: true, changed: false, fav: false, saved: false}),
    radio_information_vfo_a_tx: ref({ desc: 'RADIO INFORMATION VFO-A TX', value: null, all: true, changed: false, fav: false, saved: false}),
    radio_information_vfo_b_tx: ref({ desc: 'RADIO INFORMATION VFO-B TX', value: null, all: true, changed: false, fav: false, saved: false}),
    radio_status: ref({ desc: 'RADIO STATUS', value: null, all: true, changed: false, fav: false, saved: false}),
    read_meter_alc: ref({ desc: 'READ METER ALC', value: null, all: true, changed: false, fav: false, saved: false}),
    read_meter_front_panel: ref({ desc: 'READ METER FRONT PANEL', value: null, all: true, changed: false, fav: false, saved: false}),
    read_meter_swr: ref({ desc: 'READ METER SWR', value: null, all: true, changed: false, fav: false, saved: false}),
    rf_attenuator: ref({ desc: 'RF ATTENUATOR', value: null, all: true, changed: false, fav: false, saved: false}),
    rf_gain: ref({ desc: 'RF GAIN', value: null, all: true, changed: false, fav: false, saved: false}),
    s_meter_reading: ref({ desc: 'S-METER READING', value: null, all: true, changed: false, fav: false, saved: false}),
    speech_processor: ref({ desc: 'SPEECH PROCESSOR', value: null, all: true, changed: false, fav: false, saved: false}),
    speech_processor_level: ref({ desc: 'SPEECH PROCESSOR LEVEL', value: null, all: true, changed: false, fav: false, saved: false}),
    speech_processor_on: ref({ desc: 'SPEECH PROCESSOR ON/OFF', value: null, all: true, changed: false, fav: false, saved: false}),
    squelch_level: ref({ desc: 'SQUELCH LEVEL', value: null, all: true, changed: false, fav: false, saved: false}),
    squelclh_level: ref({ desc: 'SQUELCLH LEVEL', value: null, all: true, changed: false, fav: false, saved: false}),
    time: ref({ desc: 'TIME', value: null, all: true, changed: false, fav: false, saved: false}),
    time_differential: ref({ desc: 'TIME DIFFERENTIAL', value: null, all: true, changed: false, fav: false, saved: false}),
    transmit: ref({ desc: 'TX SET', value: null, all: true, changed: false, fav: false, saved: false}),
    tuner: ref({ desc: 'ANTENNA TUNER CONTROL', value: null, all: true, changed: false, fav: false, saved: false}),
    tx_clar: ref({ desc: 'TX CLAR', value: null, all: true, changed: false, fav: false, saved: false}),
    txw: ref({ desc: 'TXW', value: null, all: true, changed: false, fav: false, saved: false}),
    vfo_a: ref({ desc: 'FREQUENCY VFO-A', value: null, all: true, changed: false, fav: false, saved: false}),
    vfo_b: ref({ desc: 'FREQUENCY VFO-B', value: null, all: true, changed: false, fav: false, saved: false}),
    vox_delay_time: ref({ desc: 'VOX DELAY TIME', value: null, all: true, changed: false, fav: false, saved: false}),
    vox_gain: ref({ desc: 'VOX GAIN', value: null, all: true, changed: false, fav: false, saved: false}),
    vox_status: ref({ desc: 'VOX STATUS', value: null, all: true, changed: false, fav: false, saved: false}),
    width: ref({ desc: 'WIDTH', value: null, all: true, changed: false, fav: false, saved: false}),
  };
})
