import { ref } from 'vue'
import { defineStore } from 'pinia'

export const useMenusStore = defineStore('menus', () => {
  const menus = {
    '1':   {desc: 'AGC FAST DELAY', value: ref(null)},
    '2':   {desc: 'AGC MID DELAY', value: ref(null)},
    '3':   {desc: 'AGC SLOW DELAY', value: ref(null)},
    '4':   {desc: 'HOME FUNCTION', value: ref(null)},
    '5':   {desc: 'MY CALL INDICATION', value: ref(null)},
    '6':   {desc: 'DISPLAY COLOR', value: ref(null)},
    '7':   {desc: 'DIMMER LED', value: ref(null)},
    '8':   {desc: 'DIMMER TFT', value: ref(null)},
    '9':   {desc: 'BAR MTR PEAK HOLD', value: ref(null)},
    '10':  {desc: 'DVS RX OUT LEVEL', value: ref(null)},
    '11':  {desc: 'DVS TX OUT LEVEL', value: ref(null)},
    '12':  {desc: 'KEYER TYPE', value: ref(null)},
    '13':  {desc: 'KEYER DOT/DASH', value: ref(null)},
    '14':  {desc: 'CW WEIGHT', value: ref(null)},
    '15':  {desc: 'BEACON INTERVAL', value: ref(null)},
    '16':  {desc: 'NUMBER STYLE', value: ref(null)},
    '17':  {desc: 'CONTEST NUMBER', value: ref(null)},
    '18':  {desc: 'CW MEMORY 1', value: ref(null)},
    '19':  {desc: 'CW MEMORY 2', value: ref(null)},
    '20':  {desc: 'CW MEMORY 3', value: ref(null)},
    '21':  {desc: 'CW MEMORY 4', value: ref(null)},
    '22':  {desc: 'CW MEMORY 5', value: ref(null)},
    '23':  {desc: 'NB WIDTH', value: ref(null)},
    '24':  {desc: 'NB REJECTION', value: ref(null)},
    '25':  {desc: 'NB LEVEL', value: ref(null)},
    '26':  {desc: 'BEEP LEVEL', value: ref(null)},
    '27':  {desc: 'TIME ZONE', value: ref(null)},
    '28':  {desc: 'GPS/232C SELECT', value: ref(null)},
    '29':  {desc: '232C RATE', value: ref(null)},
    '30':  {desc: '232C TOT', value: ref(null)},
    '31':  {desc: 'CAT RATE', value: ref(null)},
    '32':  {desc: 'CAT TOT', value: ref(null)},
    '33':  {desc: 'CAT RTS', value: ref(null)},
    '34':  {desc: 'MEM GROUP', value: ref(null)},
    '35':  {desc: 'QUICK SPLIT FREQ', value: ref(null)},
    '36':  {desc: 'TX TOT', value: ref(null)},
    '37':  {desc: 'MIC SCAN', value: ref(null)},
    '38':  {desc: 'MIC SCAN RESUME', value: ref(null)},
    '39':  {desc: 'REF FREQ ADJ', value: ref(null)},
    '40':  {desc: 'CLAR MODE SELECT', value: ref(null)},
    '41':  {desc: 'AM LCUT FREQ', value: ref(null)},
    '42':  {desc: 'AM LCUT SLOPE', value: ref(null)},
    '43':  {desc: 'AM HCUT FREQ', value: ref(null)},
    '44':  {desc: 'AM HCUT SLOPE', value: ref(null)},
    '45':  {desc: 'AM MIC SELECT', value: ref(null)},
    '46':  {desc: 'AM OUT LEVEL', value: ref(null)},
    '47':  {desc: 'AM PTT SELECT', value: ref(null)},
    '48':  {desc: 'AM PORT SELECT', value: ref(null)},
    '49':  {desc: 'AM DATA GAIN', value: ref(null)},
    '50':  {desc: 'CW LCUT FREQ', value: ref(null)},
    '51':  {desc: 'CW LCUT SLOPE', value: ref(null)},
    '52':  {desc: 'CW HCUT FREQ', value: ref(null)},
    '53':  {desc: 'CW HCUT SLOPE', value: ref(null)},
    '54':  {desc: 'CW OUT LEVEL', value: ref(null)},
    '55':  {desc: 'CW AUTO MODE', value: ref(null)},
    '56':  {desc: 'CW BK-IN TYPE', value: ref(null)},
    '57':  {desc: 'CW BK-IN DELAY', value: ref(null)},
    '58':  {desc: 'CW WAVE SHAPE', value: ref(null)},
    '59':  {desc: 'CW FREQ DISPLAY', value: ref(null)},
    '60':  {desc: 'PC KEYING', value: ref(null)},
    '61':  {desc: 'QSK DELAY TIME', value: ref(null)},
    '62':  {desc: 'DATA MODE', value: ref(null)},
    '63':  {desc: 'PSK TONE', value: ref(null) },
    '64':  {desc: 'OTHER DISP (SSB)', value: ref(null)},
    '65':  {desc: 'OTHER SHIFT (SSB)', value: ref(null)},
    '66':  {desc: 'DATA LCUT FREQ', value: ref(null)},
    '67':  {desc: 'DATA LCUT SLOPE', value: ref(null)},
    '68':  {desc: 'DATA HCUT FREQ', value: ref(null)},
    '69':  {desc: 'DATA HCUT SLOPE', value: ref(null)},
    '70':  {desc: 'DATA IN SELECT', value: ref(null) },
    '71':  {desc: 'DATA PTT SELECT', value: ref(null) },
    '72':  {desc: 'DATA PORT SELECT', value: ref(null) },
    '73':  {desc: 'DATA OUT LEVEL', value: ref(null)},
    '74':  {desc: 'FM MIC SELECT', value: ref(null)},
    '75':  {desc: 'FM OUT LEVEL', value: ref(null)},
    '76':  {desc: 'FM PKT PTT SELECT', value: ref(null)},
    '77':  {desc: 'FM PKT PORT SELECT', value: ref(null)},
    '78':  {desc: 'FM PKT TX GAIN', value: ref(null)},
    '79':  {desc: 'FM PKT MODE', value: ref(null)},
    '80':  {desc: 'RPT SHIFT 28MHz', value: ref(null)},
    '81':  {desc: 'RPT SHIFT 50MHz', value: ref(null)},
    '82':  {desc: 'RPT SHIFT 144MHz', value: ref(null)},
    '83':  {desc: 'RPT SHIFT 430MHz', value: ref(null)},
    '84':  {desc: 'ARS 144MHz', value: ref(null)},
    '85':  {desc: 'ARS 430MHz', value: ref(null)},
    '86':  {desc: 'DCS POLARITY', value: ref(null)},
    '87':  {desc: 'RADIO ID', value: ref(null)},
    '88':  {desc: 'GM DISPLAY', value: ref(null)},
    '89':  {desc: 'DISTANCE', value: ref(null)},
    '90':  {desc: 'AMS TX MODE', value: ref(null)},
    '91':  {desc: 'STANDBY BEEP', value: ref(null)},
    '92':  {desc: 'RTTY LCUT FREQ', value: ref(null)},
    '93':  {desc: 'RTTY LCUT SLOPE', value: ref(null)},
    '94':  {desc: 'RTTY HCUT FREQ', value: ref(null)},
    '95':  {desc: 'RTTY HCUT SLOPE', value: ref(null)},
    '96':  {desc: 'RTTY SHIFT PORT', value: ref(null)},
    '97':  {desc: 'RTTY POLARITY-RX', value: ref(null)},
    '98':  {desc: 'RTTY POLARITY-TX', value: ref(null)},
    '99':  {desc: 'RTTY OUT LEVEL', value: ref(null)},
    '100': {desc: 'RTTY SHIFT FREQ', value: ref(null)},
    '101': {desc: 'RTTY MARK FREQ', value: ref(null)},
    '102': {desc: 'SSB LCUT FREQ', value: ref(null)},
    '103': {desc: 'SSB LCUT SLOPE', value: ref(null)},
    '104': {desc: 'SSB HCUT FREQ', value: ref(null)},
    '105': {desc: 'SSB HCUT SLOPE', value: ref(null)},
    '106': {desc: 'SSB MIC SELECT', value: ref(null)},
    '107': {desc: 'SSB OUT LEVEL', value: ref(null)},
    '108': {desc: 'SSB PTT SELECT', value: ref(null)},
    '109': {desc: 'SSB PORT SELECT', value: ref(null)},
    '110': {desc: 'SSB TX BPF', value: ref(null)},
    '111': {desc: 'APF WIDTH', value: ref(null)},
    '112': {desc: 'CONTOUR LEVEL', value: ref(null)},
    '113': {desc: 'CONTOUR WIDTH', value: ref(null)},
    '114': {desc: 'IF NOTCH WIDTH', value: ref(null)},
    '115': {desc: 'SCP DISPLAY MODE', value: ref(null)},
    '116': {desc: 'SCP SPAN FREQ', value: ref(null)},
    '117': {desc: 'SPECTRUM COLOR', value: ref(null)},
    '118': {desc: 'WATER FALL COLOR', value: ref(null)},
    '119': {desc: 'PRMTRC EQ1 FREQ', value: ref(null)},
    '120': {desc: 'PRMTRC EQ1 LEVEL', value: ref(null)},
    '121': {desc: 'PRMTRC EQ1 BWTH', value: ref(null)},
    '122': {desc: 'PRMTRC EQ2 FREQ', value: ref(null)},
    '123': {desc: 'PRMTRC EQ2 LEVEL', value: ref(null)},
    '124': {desc: 'PRMTRC EQ2 BWTH', value: ref(null)},
    '125': {desc: 'PRMTRC EQ3 FREQ', value: ref(null)},
    '126': {desc: 'PRMTRC EQ3 LEVEL', value: ref(null)},
    '127': {desc: 'PRMTRC EQ3 BWTH', value: ref(null)},
    '128': {desc: 'P-PRMTRC EQ1 FREQ', value: ref(null)},
    '129': {desc: 'P-PRMTRC EQ1 LEVEL', value: ref(null)},
    '130': {desc: 'P-PRMTRC EQ1 BWTH', value: ref(null)},
    '131': {desc: 'P-PRMTRC EQ2 FREQ', value: ref(null)},
    '132': {desc: 'P-PRMTRC EQ2 LEVEL', value: ref(null)},
    '133': {desc: 'P-PRMTRC EQ2 BWTH', value: ref(null)},
    '134': {desc: 'P-PRMTRC EQ3 FREQ', value: ref(null)},
    '135': {desc: 'P-PRMTRC EQ3 LEVEL', value: ref(null)},
    '136': {desc: 'P-PRMTRC EQ3 BWTH', value: ref(null)},
    '137': {desc: 'HF TX MAX POWER', value: ref(null)},
    '138': {desc: '50M TX MAX POWER', value: ref(null)},
    '139': {desc: '144M TX MAX POWER', value: ref(null)},
    '140': {desc: '430M TX MAX POWER', value: ref(null)},
    '141': {desc: 'TUNER SELECT', value: ref(null)},
    '142': {desc: 'VOX SELECT', value: ref(null)},
    '143': {desc: 'VOX GAIN', value: ref(null)},
    '144': {desc: 'VOX DELAY', value: ref(null)},
    '145': {desc: 'ANTI VOX GAIN', value: ref(null)},
    '146': {desc: 'DATA VOX GAIN', value: ref(null)},
    '147': {desc: 'DATA VOX DELAY', value: ref(null)},
    '148': {desc: 'ANTI DVOX GAIN', value: ref(null)},
    '149': {desc: 'EMERGENCY FREQ TX', value: ref(null)},
    '150': {desc: 'PRT/WIRES FREQ', value: ref(null)},
    '151': {desc: 'PRESET FREQUENCY', value: ref(null)},
    '152': {desc: 'SEARCH SETUP', value: ref(null)},
    '153': {desc: 'WIRES DG-ID', value: ref(null)},
  };

  return { menus }
})
